# Generated by Django 3.1.7 on 2021-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_cliente_peluquero_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='peluquero',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='peluquero',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
