# Generated by Django 3.1.7 on 2021-03-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0003_auto_20210329_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('estaAbonado', models.BooleanField(default=False)),
                ('montoTotal', models.FloatField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.cliente')),
                ('peluquero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.peluquero')),
            ],
        ),
    ]
