# Generated by Django 3.1.7 on 2021-03-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_metododepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodoDePago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.metododepago'),
        ),
    ]
