# Generated by Django 3.1.7 on 2021-03-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, null=True)),
                ('razonSocial', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('telefono2', models.CharField(max_length=50, null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Peluquero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('mail', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.domicilio')),
            ],
        ),
    ]
